# Generated by Django 5.0.2 on 2024-06-26 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_article_comment_rename_user_mymodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otzyv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(help_text='Название компании', max_length=100, unique=True)),
                ('text', models.TextField(help_text='Текст отзыва', unique=True)),
                ('Evaluation', models.IntegerField(default=1, help_text='Оценка', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.RemoveField(
            model_name='likedislike',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='likedislike',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='likedislike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='likedislike',
            name='vote',
        ),
    ]
