# Generated by Django 5.0.2 on 2024-06-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_otzyv_delete_article_delete_comment_delete_mymodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otzyv',
            name='minus',
            field=models.CharField(default=' ', help_text='Минусы', max_length=2000),
        ),
        migrations.AddField(
            model_name='otzyv',
            name='plus',
            field=models.CharField(default=' ', help_text='Плюсы', max_length=2000),
        ),
    ]
