# Generated by Django 5.0.2 on 2024-06-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_otzyv_minus_otzyv_plus'),
    ]

    operations = [
        migrations.AddField(
            model_name='otzyv',
            name='Image',
            field=models.ImageField(default='tasks/static/images/Shaurum.png', help_text='Картинка', upload_to=''),
        ),
    ]
